template:
  - sensor:
      - name: "Onduleur priorité de source TXT"
        #unique_id: "onduleur_priorite_source_txt"
        state: >
          {% set value_map = {
            0: "Utility first",
            1: "Solar first",
            2: "SBU first"
          } %}
          {% set sensor_value = states('sensor.onduleur_priorite_de_source') | int %}
          {{ value_map.get(sensor_value, 'Unknown') }}

      - name: "Onduleur priorité de charge TXT"
        #unique_id: "onduleur_priorite_source_txt"
        state: >
          {% set value_map = {
            0: "Utility first", 
            1: "Solar first", 
            2: "Solar + Utility", 
            3: "Only solar charging permitted" 
          } %}
          {% set sensor_value = states('sensor.onduleur_priorite_de_charge') | int %}
          {{ value_map.get(sensor_value, 'Unknown') }}

      - name: "Onduleur status comm USB"
        state: "{{ is_state('input_boolean.mon_status', 'on') }}"
        icon: >
          {% if is_state('input_boolean.mon_status', 'on') %}
            mdi:check-circle-outline
          {% else %}
            mdi:alert-circle-outline
          {% endif %}

      - name: "EDF - Type de jour tempo aujourd'hui"
        #unique_id: "onduleur_priorite_source_txt"
        state: >
          {% set value_map = {
            0: "Pas communiqué", 
            1: "Bleu", 
            2: "Blanc", 
            3: "Rouge" 
          } %}
          {% set sensor_value = states('sensor.edf_code_jour_aujourd_hui') | int %}
          {{ value_map.get(sensor_value, 'Unknown') }}

      - name: "EDF - Type de jour tempo demain"
        #unique_id: "onduleur_priorite_source_txt"
        state: >
          {% set value_map = {
            0: "Pas communiqué", 
            1: "Bleu", 
            2: "Blanc", 
            3: "Rouge" 
          } %}
          {% set sensor_value = states('sensor.edf_tempo_demain') | int %}
          {{ value_map.get(sensor_value, 'Unknown') }}

      - name: "Onduleur - Puissance tirée sur EDF"
        device_class: energy
        state_class: total
        unit_of_measurement: "W"  # Assurez-vous que l'unité est correcte selon vos besoins
        state: >
          {% if is_state('binary_sensor.onduleur_recharge_batterie_solaire', 'off')  %}
            {{ states('sensor.onduleur_active_power') }}
          {% else %}
            0
          {% endif %}
